OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "When a POKéMON battle starts, the one\n"
	.string "at the left of the list goes out first.\p"
	.string "Try switching around the order so one\n"
	.string "POKéMON doesn't get too overleveled.\l"
	.string "Otherwise, your other POKéMON will\p"
	.string "suck and not be able to win in battle.$"

